# Generated by Django 3.2.5 on 2021-08-06 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task3', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApiRequests',
            new_name='Pokemon',
        ),
    ]
